### ISSUE TITLE
Suggestion: Use Zenhub for easy workflow

### ISSUE THREAD

**Issue by ghost** [IIITians-Network/Home#26]
Step 1: Install Zenhub for Github
Step 2: Download [Zenhub chrome extension](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd?utm_source=chrome-ntp-icon)

**Comment by IIITiansNetwork** [comment]
Thank you Mr. Joshua. We followed the same.

**Comment by vibhanshujainiiitr** [comment]
Mr. Joshua, if possible please guide how to use it, as most of us are very new in this field.

**Comment by ghost** [comment]
We will have a meet soon with the dev team

**Comment by prashantkatiyar9777** [comment]
@JoshuaPoddoku I loved the concept of Zenhub and used it in all our organizations
Also, I integrated it with Slack. 
But this is a 14-day free service. What do you do after it?

**Comment by ghost** [comment]
@prashantkatiyar9777 , Zenhub for Github is free. You can check it [here](https://github.com/marketplace/zenhub) and [download ](https://chrome.google.com/webstore/detail/zenhub-for-github/ogcgkffhplmphkaahpmffcafajaocjbd)Zenhub browser extension
